import type { QuoteAIDisclosure } from '../../lib/quote-ai-disclosure';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';

export function AssistantDisclosure({ locale, processing, onClose }: { locale: 'fr' | 'en'; processing: QuoteAIDisclosure; onClose: () => void }) {
  const t = (fr: string, en: string) => locale === 'fr' ? fr : en;
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="qp-modal"><DialogHeader>
    <DialogTitle>{t('Traitement par l’assistant', 'Assistant data processing')}</DialogTitle>
    <DialogDescription>{t(`L'assistant transmet votre message, la conversation récente et l'intégralité du brouillon de travail actuel à ${processing.providerName}. Cela comprend les coordonnées du client et de l'entreprise copiées dans ce devis, les informations de TVA, la référence et les dates du devis, le projet et l'adresse du chantier, les conditions, les remises, toutes les lignes et sections, ainsi que les montants calculés. Il ne transmet pas les autres devis, les anciennes versions publiées, les répertoires de fiches réutilisables ni les identifiants secrets.`, `The assistant sends your current message, recent conversation and the complete current Working Draft to ${processing.providerName}. This includes copied Customer and business details, VAT information, the Quote reference and dates, project and work-site details, terms, discounts, every line and section, and calculated amounts. It does not send unrelated Quotes, older Published Revisions, reusable-record directories or credentials.`)}</DialogDescription>
  </DialogHeader>
    <p>{t(`Ce partage est plus large que l'ancien contexte limité aux travaux. Ne saisissez pas de données sensibles, confidentielles ou de données réelles de clients avant l'examen du fournisseur, de l'offre, de la région, des durées de conservation et des conditions de traitement pour l'usage prévu. Le fournisseur peut conserver ou utiliser les données selon ses conditions. Ce changement n'autorise pas l'utilisation de données réelles.`, `This is broader sharing than the earlier work-only context. Do not enter sensitive, confidential or real Customer data until the provider, plan, region, retention and data-processing terms have been reviewed for your intended use. The provider may retain or use submitted data under its terms. This change does not approve real-data use.`)}</p>
    <p>{t(`L'assistant ne peut modifier que les champs pris en charge dans ce brouillon. Les coordonnées du client et de l'entreprise copiées ici concernent uniquement ce devis. Vérifiez les quantités, les prix et les descriptions avant publication. L'assistant ne peut pas créer un devis ou un brouillon ultérieur, publier, envoyer, accepter ni annuler une action. Utilisez les commandes manuelles pour publier ou annuler une action.`, `The assistant can change only supported fields in this Working Draft. Copied Customer and business details belong to this Quote only. Review quantities, prices and wording before Publication. The assistant cannot create a Quote or later Working Draft, publish, send, accept or perform Undo. Use the manual controls for Publication and Undo.`)}</p>
    <p>{t(`Easy Quote n'écrit pas les conversations, brouillons ou données transmises au fournisseur dans les journaux de l'application. Lorsque le débogage est activé, la personne autorisée à consulter le devis peut voir temporairement les requêtes exactes de l'application et les appels d'outils tentés. Ces informations peuvent contenir le brouillon complet et les coordonnées du client.`, `Easy Quote does not write raw conversations, drafts or provider payloads to application logs. When debug mode is enabled, the authorized Quote viewer can see the exact application-level requests and attempted tool calls temporarily. These can contain the complete Working Draft and Customer details.`)}</p>
    <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noreferrer" className="underline">{t('Conditions de l’API Gemini', 'Gemini API terms')}</a>
    <div className="qp-modal-actions"><Button variant="outline" onClick={onClose}>{t('Fermer', 'Close')}</Button></div>
  </DialogContent></Dialog>;
}
